---
- name: Install java 8 & tomcat 9
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: yes  
    state: present

- name: Download game of life
  ansible.builtin.copy:
    src: "{{ gol_url }}"
    dest: "{{ tomcat_dest }}"
    remote_src: yes
  notify:
    - restart tomcat9
