---
- name: Install java 8 & tomcat 9
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: yes  
    state: present

- name: Download game of life
  ansible.builtin.get_url:
    url: "{{ gol_url }}"
    dest: "{{ tomcat_dest }}"
  notify:
    - restart tomcat9
